### ISSUE TITLE
Power sleep states not supported by ESP32-C3

### ISSUE THREAD

**Issue by stuartlt** [afpineda/OpenSourceSimWheelESP32#2]
**Describe the bug**
When using an ESP32-C3 (which works fine for setup1) the power states are not supported. This is similar to this issue (https://github.com/esphome/issues/issues/2575)

**To Reproduce**
1. Compile project (example Setup1) when using an ESP32-C3.

**Expected behavior**
Expect the code to support the C3 sleep states when selecting that as a target.

**Screenshots**
power.cpp: In function 'void power::begin(const gpio_num_t*, uint8_t, bool)':
power.cpp:62:7: error: 'rtc_gpio_deinit' was not declared in this scope
       rtc_gpio_deinit((gpio_num_t)p);
       ^~~~~~~~~~~~~~~
power.cpp:62:7: note: suggested alternative: 'rtc_gpio_mode_t'
       rtc_gpio_deinit((gpio_num_t)p);
       ^~~~~~~~~~~~~~~
       rtc_gpio_mode_t
power.cpp: In function 'void power::begin(gpio_num_t, bool)':
power.cpp:78:7: error: 'rtc_gpio_deinit' was not declared in this scope
       rtc_gpio_deinit((gpio_num_t)p);
       ^~~~~~~~~~~~~~~
power.cpp:78:7: note: suggested alternative: 'rtc_gpio_mode_t'
       rtc_gpio_deinit((gpio_num_t)p);
       ^~~~~~~~~~~~~~~
       rtc_gpio_mode_t
power.cpp: In function 'void enterDeepSleep()':
power.cpp:166:21: error: 'esp_sleep_enable_ext1_wakeup' was not declared in this scope
     ESP_ERROR_CHECK(esp_sleep_enable_ext1_wakeup(ext1_wakeup_sources, ext1_wakeup_mode));
esp_err.h:116:30: note: in definition of macro 'ESP_ERROR_CHECK'
         esp_err_t err_rc_ = (x);                                        \
                              ^
power.cpp:166:21: note: suggested alternative: 'esp_sleep_enable_wifi_wakeup'
     ESP_ERROR_CHECK(esp_sleep_enable_ext1_wakeup(ext1_wakeup_sources, ext1_wakeup_mode));
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
esp32\hardware\esp32\2.0.11/tools/sdk/esp32c3/include/esp_common/include/esp_err.h:116:30: note: in definition of macro 'ESP_ERROR_CHECK'
         esp_err_t err_rc_ = (x);                                        \

**DevKit board:**
 - Manufacturer: N/A
 - Model: ESP32-C3
 - Revision (if any): Super Mini 

**Additional context**
I commented out the power sleep functions to bypass this, as I was hardwiring using USB. However anyone using battery or worried about power consumption will need to swap the sleep states to match those of the C3.

**Comment by afpineda** [comment]
Sorry for the delay. I've been on holidays. 
Will look into it, however, the issue seems related to the underlying ESP32 API. Maybe, I can provide a workaround, but not a complete solution. 
Will take some time.

**Comment by afpineda** [comment]
The file "power.cpp" has been updated (version 2.3.3) to make use of the different power management API that ESP32C3 boards exposes. However, I don't own an ESP32C3 devKit, so **the code can not be tested** right now. 

The relevant test unit is "deepSleep.ino", but an slightly different test unit is needed, since the originial ESP32 devKit used for testing have a different pin-out.

If someone do the testing, please, leave a comment.

**Comment by stuartlt** [comment]
Awesome thank you. I will test once my next esp32 c3 arrives, got 2 in the mail so should be within next week or so. Thanks for your help and great project.

**Comment by afpineda** [comment]
If you switch to the _develpment_ branch, there is a new test unit for this: "DeepSleepTestESP32C3". 

Note that you should not build your own firmware from this branch (except for that test unit). It won't work. I'm waiting for a bug fix in the [NimBLE-Arduino library](https://github.com/h2zero/NimBLE-Arduino).
