### ISSUE TITLE
HELP: Funky Problem - Push buttom

### ISSUE THREAD

**Issue by FRS78** [afpineda/OpenSourceSimWheelESP32#4]
Hi all,

I have implemented Setup1 in my steering wheel project and everything works correctly except for the funky switch (RKJXT1F).

The problem is that when I connect the push button pin it generates a conflict and the funky stops working and only the push function works (and that function activates two things, the push and the crosshead up).
If I don't connect the push button pin, the funky works correctly (except the push button).

I have checked everything and it is correct (same way that the original project), but it does not work on my PCB or on my PROTOBOARD.

Please, has anyone had this problem and knows how to solve it?

![PCB Screenshoot](https://github.com/afpineda/OpenSourceSimWheelESP32/assets/139258775/e6e39dda-1711-4746-b32c-35e7d916cc8e)

**Comment by FRS78** [comment]
Added full screenshoot
![PCB Screenshoot](https://github.com/afpineda/OpenSourceSimWheelESP32/assets/139258775/b5198d4f-a95c-4cf0-aa0f-d563bfe2e691)

**Comment by janc18** [comment]
Hi @FRS78, What is your test circuit?
I just see an issue with the S1-AZUL, at the datasheet say that is  the common push pin, but you are taking like another switch.

**Comment by FRS78** [comment]
Hi @janc18 


I do not understand what you mean...

I have made a summary of how I have it connected. I think it is the same as the original project defines it.

If you see something strange, tell me because that may be the error and I won't see it.

Hope to solve this, because i expend so much time with this issue, jrjrjrjrjrjr


![Esquematic Screenshoot](https://github.com/afpineda/OpenSourceSimWheelESP32/assets/139258775/22d5bf7b-b4f1-4f51-9b76-b6deeb5291b3)
![Funky Layout](https://github.com/afpineda/OpenSourceSimWheelESP32/assets/139258775/3c007bf9-cb6b-4b05-b43f-2dec3f036371)

**Comment by afpineda** [comment]
Hi, Fernando.

I will look into this issue as soon as I can, but it can take some time.
I have an ALPS enconder over here, so I can do some testing.

Don't discard a faulty hardware design, since *setup1* was not built for a full system test (just the firmware was tested).

**Comment by afpineda** [comment]
Hello again, Fernando.

> I have been studying the topic and I already understand what you were referring to. It seems that the configuration in this funky switch the push button cannot be connected in any way that is an independent button... Can you confirm that this is the case???

I think there is a **big mistake** in the ALPS datasheet you posted before that is misleading you.

![ALPS_sheet_mistake](https://github.com/afpineda/OpenSourceSimWheelESP32/assets/74291754/a8f6c9ce-ec96-4e2b-95fc-23492539aadf)

Try to swap `COM`  and `Push` terminals and tell us what happens.

**Comment by janc18** [comment]
> I have been studying the topic and I already understand what you were referring to. It seems that the configuration in this funky switch the push button cannot be connected in any way that is an independent button... Can you confirm that this is the case???
> 

Hi @FRS78, yeah, that was exactly what I was trying to explain.
I will give the documentation a read to find an alternative.

**Comment by FRS78** [comment]
Hi @janc18 and @afpineda

Confirmed, if you connect the push pin to gpio22 and the com pin to gpio4 everything works correctly. What's more, I have verified that the rest of the buttons work correctly, including the ALT buttons.

What remains pending is:
Option 1: Document this change in the original schematic
Option 2: edit the code

**Comment by FRS78** [comment]
Post-data (spanish)

Muchas gracias por vuestra colaboración @janc18 / @afpineda 
Estaba atascado con esto y no veía la luz

Aprovecho para felicitaros por este proyecto porque es Super chulo, muy flexible y funcional
Una verdadera lástima no poder usar estas preciosas PCB´s que ya tengo hechas:

![PCB](https://github.com/afpineda/OpenSourceSimWheelESP32/assets/139258775/a4e3b5bf-6589-4589-88e8-3a73884b2406)


Lo que voy a hacer es editar mi PBC para tener la funcionalidad TOTAL del proyecto, por eso si se cambia el código por favor haced un post para reactualizar las PCB´s si hiciera falta (aunque lo más práctico es modificar el esquemático original del proyecto y fin del problema)

Saludos y muchas gracias por vuestra atención

**Comment by janc18** [comment]
Hi @FRS78 and @afpineda.

If anyone has a problem in the future or needs help or feedback, don't hesitate to contact me. We have somewhat similar projects in the achievement of DIY equipment for simracing.

**Comment by afpineda** [comment]
Hi.

> What remains pending is: Option 1: Document this change in the original schematic Option 2: edit the code

The mistake is at the ALPS datasheet. The code and the circuit design is not faulty, nor your printed PCB is. I feel sorry for you. 
This is the second time a misleading tag is causing an issue.
